<a href="https://colab.research.google.com/github/nvarghese-u2can/Natural-Language-Processing---MyLearningProjects/blob/main/BERT_Model_Exploration_withTFHub.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# BERT Model exploration using the TF Hub models

**Install the dependcies**

In [43]:
!pip3 install tensorflow_text

In [44]:
!pip3 install tensorflow_hub

In [45]:
import tensorflow_hub as hub
import tensorflow_text as text

import the preprocess and encoder urls from the TF Hub

https://tfhub.dev/google/collections/bert/1

https://tfhub.dev/tensorflow/bert_en_uncased_L-12_H-768_A-12/4


In [46]:
preprocess_url = 'https://tfhub.dev/tensorflow/bert_en_uncased_preprocess/3'
bert_model_url = 'https://tfhub.dev/tensorflow/bert_en_uncased_L-12_H-768_A-12/4'
# bert_model_url ='https://tfhub.dev/tensorflow/bert_en_wwm_uncased_L-24_H-1024_A-16/4'

In [47]:
bert_preprocess_model = hub.KerasLayer(preprocess_url)

In [48]:
test_data = ['I like Hugging Face Hub','I like Tensorflow Hub']
test_data_preprocessed = bert_preprocess_model(test_data)

In [49]:
type(test_data_preprocessed ),test_data_preprocessed.keys()

(dict, dict_keys(['input_type_ids', 'input_mask', 'input_word_ids']))

In [50]:
test_data_preprocessed

{'input_mask': <tf.Tensor: shape=(2, 128), dtype=int32, numpy=
 array([[1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],
       dtype=int32)>,
 'input_type_ids': <tf.Tensor: shape

In [51]:
bert_model = hub.KerasLayer(bert_model_url)

In [52]:
bert_model_outputs = bert_model(test_data_preprocessed)

In [53]:
type(bert_model_outputs),bert_model_outputs.keys()

(dict,
 dict_keys(['sequence_output', 'pooled_output', 'default', 'encoder_outputs']))

In [54]:
# Sentence embedding output vectors, each with size 768 
bert_model_outputs['pooled_output']

<tf.Tensor: shape=(2, 768), dtype=float32, numpy=
array([[-0.79370034, -0.1636735 ,  0.5892364 , ...,  0.29831108,
        -0.50660676,  0.8665213 ],
       [-0.8412268 , -0.2896706 , -0.2755478 , ..., -0.25516403,
        -0.58974826,  0.88071877]], dtype=float32)>

In [55]:
bert_model_outputs['sequence_output']

<tf.Tensor: shape=(2, 128, 768), dtype=float32, numpy=
array([[[-1.12827718e-02,  1.63289666e-01,  1.75957561e-01, ...,
         -2.00993732e-01,  1.59414113e-03,  2.85197169e-01],
        [ 7.03652427e-02,  6.23687282e-02, -1.65635183e-01, ...,
         -2.34718338e-01,  5.27107179e-01, -9.26827863e-02],
        [-9.99593735e-02,  2.07693815e-01,  1.06874347e+00, ...,
         -5.02662659e-01, -3.45538184e-03,  4.63096946e-02],
        ...,
        [ 2.97285765e-02,  8.72131437e-02,  4.61569428e-01, ...,
          1.08076096e-01, -7.73734972e-02,  2.15053737e-01],
        [-1.26957372e-01,  1.14687227e-01,  4.71061409e-01, ...,
          9.44351852e-02, -1.66642159e-01,  2.78010815e-01],
        [-1.03171363e-01,  1.01493925e-01,  4.96349484e-01, ...,
          8.16526189e-02, -1.47772014e-01,  2.15934411e-01]],

       [[-1.24179646e-02, -6.47819191e-02, -6.68492541e-02, ...,
         -2.04981029e-01,  1.67073637e-01,  5.93626380e-01],
        [ 2.43022650e-01, -2.34353811e-01, -2.22

In [56]:
# Chosen BERT encoder model has 12 encoder layers  - bert_en_uncased_L-12_H-768_A-12/4
len(bert_model_outputs['encoder_outputs'])

12

In [57]:
# Output from the 12 the layer of the Encoder is same as the bert_model_outputs['sequence_output']
bert_model_outputs['encoder_outputs'][-1] == bert_model_outputs['sequence_output']

<tf.Tensor: shape=(2, 128, 768), dtype=bool, numpy=
array([[[ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        ...,
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True]],

       [[ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        ...,
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True]]])>